#!/bin/bash
find . -name "*.html" -type f | while read -r file; do if [ "$file" -nt "../$(basename "$file")" ]; then cp "$file" "../$(basename "$file")"; echo "$file copied to parent directory"; fi; done
