#!/usr/bin/env bash
# changes the following domain resolve ips
#   localhost from 127.0.0.1 to 127.0.0.2
#   facebook.com from 157.240.11.35 to 8.8.8.8

sudo sed -i 's/localhost$/localhost\n127.0.0.2/' /etc/hosts
sudo sed -i 's/facebook.com/8.8.8.8 facebook.com/' /etc/hosts
sudo service systemd-resolved restart

