#!/usr/bin/env bash
# changes the following domain resolve ips
#   localhost from 127.0.0.1 to 127.0.0.2
#   facebook.com from 157.240.11.35 to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i 's/127\.0\.0\.1[[:space:]]*localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/facebook.com[[:space:]]*[0-9.]*[[:space:]]*facebook.com/8.8.8.8 facebook.com/' /etc/hosts
sudo systemd-resolve --flush-caches
