#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.

interfaces=$(ip -4 -o addr show | awk '{print $2}')

for interface in $interfaces; do
  # Get the IPv4 address for the interface
  ip_address=$(ip -4 -o addr show dev $interface | awk '{print $4}')

  # Exclude loopback addresses
  if [[ $ip_address != 127.* ]]; then
    echo $ip_address
  fi
done

