#!/usr/bin/env bash
# SSH Config File

Host *
	SendEnv LANG LC_*
	HashKnownHosts yes
	Hostname 35.243.128.200
	User ubuntu
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
